################################################################################
# These macros are used by makefiles and argument files.
# When a space is included in the path and quotes (") cannot be used,
# a _ESCAPE version of the macro is added that escapes the space with backslash (\).
################################################################################

export GNU_Make_Install_DirEnv=$(CWInstallLocationEnv)/gnu/bin
export ProjDirPath=C:/Freescale/Freescale_MQX_4_1_FRDMK64F/mfs/examples/sdcard/build/cw10gcc/mfs_sdcard_frdmk64f
export CWInstallLocationEnv=C:/Freescale/CW MCU v10.6
export MFS=C:/Freescale/Freescale_MQX_4_1_FRDMK64F/lib/frdmk64f.cw10gcc/release/mfs
export SDCARD=C:/Freescale/Freescale_MQX_4_1_FRDMK64F/mfs/examples/sdcard
export ARMSourceryDirEnv=$(CWInstallLocationEnv)/Cross_Tools/arm-none-eabi-gcc-4_7_3/bin
export SHELL1=C:/Freescale/Freescale_MQX_4_1_FRDMK64F/lib/frdmk64f.cw10gcc/release/shell
export FREESCALE=C:/Freescale
export BSP=C:/Freescale/Freescale_MQX_4_1_FRDMK64F/lib/frdmk64f.cw10gcc/release/bsp
export PSP=C:/Freescale/Freescale_MQX_4_1_FRDMK64F/lib/frdmk64f.cw10gcc/release/psp
